In [1]:
import numpy as np

In [2]:
ar6=np.arange(1,10,2)
print(ar6)

[1 3 5 7 9]


In [3]:

ar7=np.linspace(1,20,10)
print(ar7)

[ 1.          3.11111111  5.22222222  7.33333333  9.44444444 11.55555556
 13.66666667 15.77777778 17.88888889 20.        ]


In [4]:

ar6*4

array([ 4, 12, 20, 28, 36])

In [5]:

ar6%3==0

array([False,  True, False, False,  True])

In [6]:
ar7[4:]=10
print(ar7)

[ 1.          3.11111111  5.22222222  7.33333333 10.         10.
 10.         10.         10.         10.        ]


In [7]:

ar7[4:8:2]=15
print(ar7)

[ 1.          3.11111111  5.22222222  7.33333333 15.         10.
 15.         10.         10.         10.        ]


In [8]:

ar8=[14,62,33,77,85,92]
print(ar8)

[14, 62, 33, 77, 85, 92]


In [9]:
print(np.random.rand(3,3))

[[0.74819151 0.62991277 0.30015582]
 [0.71739963 0.55498482 0.16288024]
 [0.00181373 0.94045289 0.69169417]]


In [12]:

print(np.random.randn(3,4))

[[ 1.83707137  1.91136232  0.70412131  0.29198549]
 [-0.7834235   0.30166828  2.84063905 -0.28007181]
 [-2.15716952 -0.72160384 -1.1565895   0.19037057]]
