In [1]:
import numpy as np

In [2]:
e1=[6,2,8,9,]
ar=np.array(e1)
print(ar)
print(type(ar))

[6 2 8 9]
<class 'numpy.ndarray'>


In [3]:
print(ar.shape)

(4,)


In [5]:
print(ar[2])
print(ar[1])

8
2


In [10]:
print(ar.reshape(1,4))
print(ar.reshape(4,1))

[[6 2 8 9]]
[[6]
 [2]
 [8]
 [9]]


In [12]:
arr=ar.reshape(1,4)
ara=ar.reshape(4,1)
print(arr.shape)
print(ara.shape)

(1, 4)
(4, 1)


In [15]:
e2=[4,5,6]
e3=[6,7,8]
e4=[8,2,5]
ary=np.array([e2,e3,e4])
print(type(ary))
print(ary)
print(ary.shape)

<class 'numpy.ndarray'>
[[4 5 6]
 [6 7 8]
 [8 2 5]]
(3, 3)


In [16]:
print(ary.reshape(1,9))
print(ary.reshape(9,1))


[[4 5 6 6 7 8 8 2 5]]
[[4]
 [5]
 [6]
 [6]
 [7]
 [8]
 [8]
 [2]
 [5]]
