In [5]:
import numpy as np

In [6]:
e1=[6,2,8,9,]
ar=np.array(e1)
print(ar)
print(type(ar))

[6 2 8 9]
<class 'numpy.ndarray'>


In [7]:
print(ar.shape)

(4,)


In [8]:
print(ar[2])
print(ar[1])

8
2


In [9]:
print(ar.reshape(1,4))
print(ar.reshape(4,1))

[[6 2 8 9]]
[[6]
 [2]
 [8]
 [9]]


In [10]:
arr=ar.reshape(1,4)
ara=ar.reshape(4,1)
print(arr.shape)
print(ara.shape)

(1, 4)
(4, 1)


In [11]:
e2=[4,5,6]
e3=[6,7,8]
e4=[8,2,5]
ary=np.array([e2,e3,e4])
print(type(ary))
print(ary)
print(ary.shape)

<class 'numpy.ndarray'>
[[4 5 6]
 [6 7 8]
 [8 2 5]]
(3, 3)


In [12]:
print(ary.reshape(1,9))
print(ary.reshape(9,1))

[[4 5 6 6 7 8 8 2 5]]
[[4]
 [5]
 [6]
 [6]
 [7]
 [8]
 [8]
 [2]
 [5]]


In [14]:
e5=[1,2,3,4,5]
e6=[7,8,9,0,1]
e7=[1,3,4,5,6]
e8=[7,7,2,3,4]
are=np.array([e5,e6,e7,e8])
print(are)

[[1 2 3 4 5]
 [7 8 9 0 1]
 [1 3 4 5 6]
 [7 7 2 3 4]]


In [15]:
print(are[:,:])

[[1 2 3 4 5]
 [7 8 9 0 1]
 [1 3 4 5 6]
 [7 7 2 3 4]]


In [17]:

print(are[2:,1:3])

[[3 4]
 [7 2]]


In [18]:

print(are[1:,1:])

[[8 9 0 1]
 [3 4 5 6]
 [7 2 3 4]]


In [19]:

print(are[1:3,:2])

[[7 8]
 [1 3]]
